# v4
version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: main
    directory: "."
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    target-branch: main
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    groups:
      gha:
        patterns:
          - "*"
