<template>
  <div class="docs-page">
    <h1
      id="mcp"
      class="docs-title"
    >
      Model Context Protocol
    </h1>

    <p>
      If you want to provide an MCP server for your components,
      Vue-Doxen provides a helper function to convert your component
      demos to a serialized JSON format. You can then use that JSON
      with any existing MCP server tools.
    </p>

    <nav>
      <ul>
        <li><a href="#getting-started">Getting Started</a></li>
        <li><a href="#advanced">Advanced</a></li>
      </ul>
    </nav>

    <DocumentationSection id="getting-started" title="Getting Started">
      <p>
        You will need to create a script to run the
        <code>serializeDemos</code> function from.
      </p>
      <DoxenCodeSwapper
        fileName="./scripts/generateMcpData.js"
        :codeTypes="{ JavaScript: CUSTOM_SCRIPT }"
        :styleTokens="styleTokens"
      />
      <p>
        The above script uses both features of Node.js and Vite. Once created
        you'll need a convienient way to run it. I would recommed using an npm
        script. In the example we use <code>vite-node</code>, you may need to
        run <code>npm i -D vite-node</code> for the npm script below to work.
        If you know of a way to get the script to work with
        <a
          href="https://vite.dev/guide/api-environment-runtimes.html#modulerunner"
          target="_blank"
        >Vite's ModuleRunner</a>,
        create a
        <a
          href="https://github.com/TheJaredWilcurt/vue-doxen/issues/new?title=DoxenLinter%20ModuleRunner%20example"
        >GitHub issue</a> with an example so it can be documented here.
      </p>
      <DoxenCodeSwapper
        fileName="./package.json"
        :codeTypes="{ JavaScript: PACKAGE_JSON }"
        :styleTokens="styleTokens"
      />
      <ul>
        <li><code>npm run mcp</code></li>
      </ul>
    </DocumentationSection>

    <DocumentationSection id="advanced" title="Advanced">
      <p>
        Vue-Doxen demos allow using custom components for your
        <code>description</code>, <code>importStatement</code>, etc.
        Custom Vue components can be extremely complex. In order to
        extract the information from them to serialize it as a string
        of HTML, we use Playwright to load your demo in a real browser
        and extract the rendered HTML from your custom components. This
        is then placed in the JSON object generated by
        <code>serializeDemos</code>.
      </p>
      <p>
        You'll need to install PlayWright to have access to this feature.
      </p>
      <ul>
        <li><code>npm i -D playwright</code></li>
      </ul>
      <p>
        You'll need to provide a URL to a page with both
        <code>DoxenSidebar</code> and <code>VueDoxen</code>
        (or <code>VueDoxenCustom</code>) where
        all of your demos are passed in to both components.
        How you create the local webserver (or if it is hosted
        online), and how you create the URL is up to you.
      </p>

      <DoxenCodeSwapper
        fileName="./src/views/DoxenMCP.vue"
        :codeTypes="{
          'Options API': MCP_ADVANCED_OPTIONS_EXAMPLE,
          'Composition API': MCP_ADVANCED_COMPOSITION_EXAMPLE,
          'Script Setup': MCP_ADVANCED_SCRIPT_SETUP_EXAMPLE
        }"
        :styleTokens="styleTokens"
      />

      <DoxenCodeSwapper
        fileName="./scripts/generateMcpData.js"
        :codeTypes="{ JavaScript: ADVANCED }"
        :styleTokens="styleTokens"
      />

      <DoxenCodeSwapper
        fileName="./src/demos/index.js"
        :codeTypes="{ JavaScript: ALL_DEMOS }"
        :styleTokens="styleTokens"
      />
    </DocumentationSection>
  </div>
</template>

<script>
import { styleTokens } from '@/helpers/props.js';

import DoxenCodeSwapper from '@/components/DoxenCodeSwapper.vue';
import DocumentationSection from '@@@/components/DocumentationSection.vue';

import {
  MCP_ADVANCED_OPTIONS_EXAMPLE,
  MCP_ADVANCED_COMPOSITION_EXAMPLE,
  MCP_ADVANCED_SCRIPT_SETUP_EXAMPLE
} from '@@@/helpers/codeSnippets.js';

const CUSTOM_SCRIPT = `
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { serializeDemos } from 'vue-doxen';

import { demo as MyFoo } from '../src/demos/fooDemo.js';
import { demo as MyBar } from '../src/demos/barDemo.js';
import MyBuzz from '../src/components/MyBuzz.vue';

const demos = {
  MyFoo,
  MyBar,
  MyBuzz
};

async function convertDemosToJson () {
  try {
    const data = await serializeDemos(demos);
    const content = JSON.stringify(data, null, 2) + '\\n';
    const outputFile = join(import.meta.dirname, 'demos.json');
    fs.writeFileSync(outputFile, content);
  } catch (error) {
    console.log(error);
  }
}

convertDemosToJson();
`.trim();

const PACKAGE_JSON = `
{
  "scripts": {
    "mcp": "vite-node --config vite.config.js ./scripts/generateMcpData.js"
  }
}
`.trim();
const ADVANCED = `
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { serializeDemos } from 'vue-doxen';

import { allDemos } from '../src/demos/index.js';

async function convertDemosToJson () {
  try {
    // A URL to a webpage with all the demos loaded
    const url = 'https://localhost:8080/doxen-mcp';

    const data = await serializeDemos(allDemos, url);
    const content = JSON.stringify(data, null, 2) + '\\n';

    const outputFile = join(import.meta.dirname, 'demos.json');
    fs.writeFileSync(outputFile, content);
  } catch (error) {
    console.log(error);
  }
}

convertDemosToJson();
`.trim();

const ALL_DEMOS = `
import { demo as MyFoo } from './fooDemo.js';
import { demo as MyBar } from './barDemo.js';
import MyBuzz from '../components/MyBuzz.vue';

export const allDemos = {
  MyFoo,
  MyBar,
  MyBuzz
};
`.trim();

export default {
  name: 'ModelContextProtocol',
  components: {
    DocumentationSection,
    DoxenCodeSwapper
  },
  props: {
    styleTokens
  },
  constants: {
    ADVANCED,
    ALL_DEMOS,
    CUSTOM_SCRIPT,
    MCP_ADVANCED_OPTIONS_EXAMPLE,
    MCP_ADVANCED_COMPOSITION_EXAMPLE,
    MCP_ADVANCED_SCRIPT_SETUP_EXAMPLE,
    PACKAGE_JSON
  }
};
</script>
