<template>
  <VueDoxenCustom
    :demos="demos"
    :options="defaultOptions"
    :modelValue="modelValue"
    :styleTokens="styleTokens"
    @update:model-value="$emit('update:model-value', $event)"
  />
</template>

<script>
import { createImportStatement } from '@/helpers/componentHelpers.js';
import defaultOptions from '@/helpers/defaultOptions.js';
import {
  createModelValueProp,
  demos,
  options,
  styleTokens
} from '@/helpers/props.js';

import VueDoxenCustom from '@/components/VueDoxenCustom.vue';

const COMPONENT_NAME = 'VueDoxen';
const modelValue = createModelValueProp(String);

export default {
  ...createImportStatement(COMPONENT_NAME),
  name: COMPONENT_NAME,
  description: [
    'This page IS the VueDoxen component. The title, usage, playground and props/emits documentation',
    'are all auto-generated by the VueDoxen component to demo YOUR component. Right now it\'s',
    'demoing itself. Pretty meta.'
  ].join(' '),
  components: {
    VueDoxenCustom
  },
  emits: ['update:model-value'],
  props: {
    demos,
    modelValue,
    options,
    styleTokens
  },
  computed: {
    defaultOptions: function () {
      return defaultOptions;
    }
  }
};
</script>
